USE master
GO

CREATE DATABASE WMS
GO

USE WMS
GO

CREATE TABLE Clients 
(
	ClientId INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL CHECK(LEN(Phone) = 12) 
)

CREATE TABLE Mechanics 
(
	MechanicId INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	[Address] VARCHAR(255) NOT NULL
)

CREATE TABLE Models 
(
	ModelId INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL UNIQUE 
)

CREATE TABLE Jobs 
(
	JobId INT IDENTITY PRIMARY KEY,
	ModelId INT NOT NULL 
		FOREIGN KEY REFERENCES Models(ModelId),

	[Status] CHAR(11) NOT NULL 
		CHECK(LEN(Status) <= 11
		  AND[Status] IN ('Pending','In Progress' ,'Finished'))
		DEFAULT 'Pending',
	ClientId INT NOT NULL
		FOREIGN KEY REFERENCES Clients(ClientId),
	MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
	IssueDate DATE NOT NULL,
	FinishDate DATE
)

CREATE TABLE Orders 
(
	OrderId INT IDENTITY PRIMARY KEY,
	JobId INT NOT NULL
	FOREIGN KEY REFERENCES Jobs(JobId),
	IssueDate DATE,
	Delivered BIT NOT NULL DEFAULT 0 
)

CREATE TABLE Vendors 
(
	VendorId INT IDENTITY PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL UNIQUE 
)


CREATE TABLE Parts 
(
	PartId INT IDENTITY PRIMARY KEY,
	SerialNumber VARCHAR(50) NOT NULL UNIQUE ,
	[Description] VARCHAR(255),
	Price DECIMAL(6,2) NOT NULL CHECK(Price > 0) ,
	VendorId INT NOT NULL
		FOREIGN KEY REFERENCES Vendors(VendorId), 
	StockQty INT CHECK(StockQty >= 0) DEFAULT 0
)

CREATE TABLE OrderParts
(
	OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderId),
	PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
	Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1 
	PRIMARY KEY(OrderId, PartId)
)

CREATE TABLE PartsNeeded
(
	JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
	PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
	Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1 
	PRIMARY KEY(JobId, PartId)
)
